#公共配置
server:
    port: 80
    tomcat:
      uri-encoding: UTF-8
spring:
  #激活哪一个环境的配置文件
  profiles:
    active: dev
  #视图配置
  mvc:
    static-path-pattern: /static/**
  #网络请求配置
  http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
      multipart:
          max-file-size: 100MB
          max-request-size: 100MB
          enabled: true
  #模板引擎配置
  freemarker:
      template-loader-path: classpath:/templates/
      prefer-file-system-access: false
      settings:
        template_update_delay: 0
        classic_compatible: true
        number_format: 0.######
        template_exception_handler: ignore
      request-context-attribute: rc
      charset: UTF-8
  #连接池配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      validationQuery: SELECT 1
      initialSize: 10
      minIdle: 10
      maxActive: 200
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100

  #缓存配置
  cache:
      type: redis
      cache-names: mysiteforme
#mybatisPlus
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mysiteforme.admin.entity
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号隔离
  typeAliasesPackage: com.mysiteforme.admin.entity

  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #    logic-delete-value: 1
    #    logic-not-delete-value: 0
    #自定义填充策略接口实现
    metaObjectHandler: com.mysiteforme.admin.config.SysMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

---
#开发环境配置
server:
  #端口
  port: 8080
spring:
  profiles: dev
  #redis配置
  redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      password:      # 密码（默认为空）
      timeout: 6000  # 连接超时时长（毫秒）
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3308/mysiteforme?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  mvc:
    static-path-pattern: /image/**
  resources:
    static-locations: file:/Users/jing/Documents/my_project/data/img/
#日志
logging:
  config: classpath:log/logback.xml
  path: D:\log\mysiteforme

#自定义配置属性
#源码生成文件夹
source-code-dic:  D://mysite
source-code-zipfile:  D://源码.rar

#搜索文件生成包的位置
#本地路径
lucence-dic: D://lucence







